inherit_gem: { standard: config/base.yml }

# AllCops:
#   TargetRubyVersion: 3.1

# Style/StringLiterals:
#   EnforcedStyle: double_quotes

# Style/StringLiteralsInInterpolation:
#   EnforcedStyle: double_quotes
